---
name: CI

"on":
  pull_request_target:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Test Sec
        env:
          REPO: ${{ secrets.REPO }}
        run: |
          python3 sec.py
